package com.vtempe.ui.screens

import com.vtempe.shared.domain.model.CoachTrainerIds
import com.vtempe.ui.Res
import com.vtempe.ui.*
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.StringResource

data class CoachTrainerUi(
    val id: String,
    val nameRes: StringResource,
    val avatar: DrawableResource
)

val coachTrainerOptions: List<CoachTrainerUi> = listOf(
    CoachTrainerUi(CoachTrainerIds.ARTUR, Res.string.coach_artur_name, Res.drawable.coach_artur_avatar),
    CoachTrainerUi(CoachTrainerIds.MIA, Res.string.coach_mia_name, Res.drawable.coach_mia_avatar),
    CoachTrainerUi(CoachTrainerIds.VTEMPE, Res.string.coach_vtempe_name, Res.drawable.coach_vtempe_avatar)
)

interface CoachVisualProvider {
    fun avatar(trainerId: String): DrawableResource
    fun exerciseIllustration(
        trainerId: String,
        exerciseId: String,
        fallback: DrawableResource
    ): DrawableResource
}

object DefaultCoachVisualProvider : CoachVisualProvider {
    override fun avatar(trainerId: String): DrawableResource =
        coachTrainerOptions.firstOrNull { it.id == normalizeCoachTrainerId(trainerId) }?.avatar
            ?: Res.drawable.coach_mia_avatar

    override fun exerciseIllustration(
        trainerId: String,
        exerciseId: String,
        fallback: DrawableResource
    ): DrawableResource {
        val normalizedTrainer = normalizeCoachTrainerId(trainerId)
        // Resolve visual alias so variant exercises share the "parent" exercise photo
        val normalizedExercise = exerciseId.lowercase().replace('-', '_')
        val lookupId = exerciseVisualAlias[normalizedExercise] ?: normalizedExercise
        return when (normalizedTrainer) {
            CoachTrainerIds.ARTUR -> arturExerciseIllustrations[lookupId]
            CoachTrainerIds.VTEMPE -> vtempeExerciseIllustrations[lookupId]
            else -> miaExerciseIllustrations[lookupId]
        } ?: fallback
    }
}

/**
 * Fallback aliases: maps an exercise ID to another when no dedicated photo exists.
 * Now that all 107 exercises have coach-specific photos, this map is intentionally
 * empty. Keep it here — if a new exercise is added to the catalog without a photo,
 * add an entry here pointing to the closest visual match.
 */
private val exerciseVisualAlias: Map<String, String> = mapOf(
    // Add entries here only for exercises without a dedicated photo:
    // "new_exercise" to "visually_similar_existing_exercise",
    "military_press_machine" to "ohp",
    "overhead_tricep_extension" to "tricep_extension",
    "chest_press_machine" to "bench",
)

fun normalizeCoachTrainerId(raw: String?): String = CoachTrainerIds.normalize(raw)

fun coachAvatarFor(trainerId: String): DrawableResource =
    DefaultCoachVisualProvider.avatar(trainerId)

fun coachExerciseIllustration(
    trainerId: String,
    exerciseId: String,
    fallback: DrawableResource
): DrawableResource =
    DefaultCoachVisualProvider.exerciseIllustration(trainerId, exerciseId, fallback)

private val arturExerciseIllustrations = mapOf(
    "squat" to Res.drawable.coach_artur_squat,
    "leg_press" to Res.drawable.coach_artur_leg_press,
    "lunge" to Res.drawable.coach_artur_lunge,
    "deadlift" to Res.drawable.coach_artur_deadlift,
    "bench" to Res.drawable.coach_artur_bench,
    "pushup" to Res.drawable.coach_artur_pushup,
    "dip" to Res.drawable.coach_artur_dip,
    "row" to Res.drawable.coach_artur_row,
    "pullup" to Res.drawable.coach_artur_pullup,
    "ohp" to Res.drawable.coach_artur_ohp,
    "curl" to Res.drawable.coach_artur_curl,
    "tricep_extension" to Res.drawable.coach_artur_tricep_extension,
    "run" to Res.drawable.coach_artur_run,
    "bike" to Res.drawable.coach_artur_bike,
    "ab_wheel" to Res.drawable.coach_artur_ab_wheel,
    "arnold_press" to Res.drawable.coach_artur_arnold_press,
    "assisted_pullup" to Res.drawable.coach_artur_assisted_pullup,
    "band_pulldown" to Res.drawable.coach_artur_band_pulldown,
    "band_row" to Res.drawable.coach_artur_band_row,
    "barbell_hack_squat" to Res.drawable.coach_artur_barbell_hack_squat,
    "battle_rope" to Res.drawable.coach_artur_battle_rope,
    "bicycle_crunch" to Res.drawable.coach_artur_bicycle_crunch,
    "box_jump" to Res.drawable.coach_artur_box_jump,
    "box_squat" to Res.drawable.coach_artur_box_squat,
    "bulgarian_split_squat" to Res.drawable.coach_artur_bulgarian_split_squat,
    "burpee" to Res.drawable.coach_artur_burpee,
    "cable_crunch" to Res.drawable.coach_artur_cable_crunch,
    "cable_curl" to Res.drawable.coach_artur_cable_curl,
    "cable_fly" to Res.drawable.coach_artur_cable_fly,
    "cable_row" to Res.drawable.coach_artur_cable_row,
    "cat_cow" to Res.drawable.coach_artur_cat_cow,
    "chest_supported_row" to Res.drawable.coach_artur_chest_supported_row,
    "chin_up" to Res.drawable.coach_artur_chin_up,
    "close_grip_bench" to Res.drawable.coach_artur_close_grip_bench,
    "concentration_curl" to Res.drawable.coach_artur_concentration_curl,
    "crunch" to Res.drawable.coach_artur_crunch,
    "dead_bug" to Res.drawable.coach_artur_dead_bug,
    "decline_pushup" to Res.drawable.coach_artur_decline_pushup,
    "diamond_pushup" to Res.drawable.coach_artur_diamond_pushup,
    "dumbbell_fly" to Res.drawable.coach_artur_dumbbell_fly,
    "dumbbell_row" to Res.drawable.coach_artur_dumbbell_row,
    "dumbbell_shoulder_press" to Res.drawable.coach_artur_dumbbell_shoulder_press,
    "elliptical" to Res.drawable.coach_artur_elliptical,
    "face_pull" to Res.drawable.coach_artur_face_pull,
    "foam_rolling" to Res.drawable.coach_artur_foam_rolling,
    "front_raise" to Res.drawable.coach_artur_front_raise,
    "front_squat" to Res.drawable.coach_artur_front_squat,
    "glute_bridge" to Res.drawable.coach_artur_glute_bridge,
    "goblet_squat" to Res.drawable.coach_artur_goblet_squat,
    "good_morning" to Res.drawable.coach_artur_good_morning,
    "hack_squat" to Res.drawable.coach_artur_hack_squat,
    "hammer_curl" to Res.drawable.coach_artur_hammer_curl,
    "handstand_pushup" to Res.drawable.coach_artur_handstand_pushup,
    "hanging_leg_raise" to Res.drawable.coach_artur_hanging_leg_raise,
    "high_knees" to Res.drawable.coach_artur_high_knees,
    "hip_flexor_stretch" to Res.drawable.coach_artur_hip_flexor_stretch,
    "hip_thrust" to Res.drawable.coach_artur_hip_thrust,
    "hollow_body" to Res.drawable.coach_artur_hollow_body,
    "incline_bench" to Res.drawable.coach_artur_incline_bench,
    "incline_curl" to Res.drawable.coach_artur_incline_curl,
    "incline_pushup" to Res.drawable.coach_artur_incline_pushup,
    "inverted_row" to Res.drawable.coach_artur_inverted_row,
    "jump_rope" to Res.drawable.coach_artur_jump_rope,
    "jump_squat" to Res.drawable.coach_artur_jump_squat,
    "jumping_jack" to Res.drawable.coach_artur_jumping_jack,
    "kettlebell_swing" to Res.drawable.coach_artur_kettlebell_swing,
    "l_sit" to Res.drawable.coach_artur_l_sit,
    "lat_pulldown" to Res.drawable.coach_artur_lat_pulldown,
    "lateral_lunge" to Res.drawable.coach_artur_lateral_lunge,
    "lateral_raise" to Res.drawable.coach_artur_lateral_raise,
    "leg_curl" to Res.drawable.coach_artur_leg_curl,
    "leg_extension" to Res.drawable.coach_artur_leg_extension,
    "leg_raise" to Res.drawable.coach_artur_leg_raise,
    "mountain_climber" to Res.drawable.coach_artur_mountain_climber,
    "muscle_up" to Res.drawable.coach_artur_muscle_up,
    "nordic_curl" to Res.drawable.coach_artur_nordic_curl,
    "pike_pushup" to Res.drawable.coach_artur_pike_pushup,
    "pistol_squat" to Res.drawable.coach_artur_pistol_squat,
    "plank" to Res.drawable.coach_artur_plank,
    "reverse_curl" to Res.drawable.coach_artur_reverse_curl,
    "reverse_lunge" to Res.drawable.coach_artur_reverse_lunge,
    "romanian_deadlift" to Res.drawable.coach_artur_romanian_deadlift,
    "rowing_machine" to Res.drawable.coach_artur_rowing_machine,
    "russian_twist" to Res.drawable.coach_artur_russian_twist,
    "side_plank" to Res.drawable.coach_artur_side_plank,
    "single_leg_deadlift" to Res.drawable.coach_artur_single_leg_deadlift,
    "skater_jump" to Res.drawable.coach_artur_skater_jump,
    "skater_lunge" to Res.drawable.coach_artur_skater_lunge,
    "skull_crusher" to Res.drawable.coach_artur_skull_crusher,
    "sprint" to Res.drawable.coach_artur_sprint,
    "stair_climb" to Res.drawable.coach_artur_stair_climb,
    "step_up" to Res.drawable.coach_artur_step_up,
    "stretching" to Res.drawable.coach_artur_stretching,
    "sumo_deadlift" to Res.drawable.coach_artur_sumo_deadlift,
    "sumo_squat" to Res.drawable.coach_artur_sumo_squat,
    "swim" to Res.drawable.coach_artur_swim,
    "t_bar_row" to Res.drawable.coach_artur_t_bar_row,
    "toes_to_bar" to Res.drawable.coach_artur_toes_to_bar,
    "tricep_kickback" to Res.drawable.coach_artur_tricep_kickback,
    "tricep_pushdown" to Res.drawable.coach_artur_tricep_pushdown,
    "upright_row" to Res.drawable.coach_artur_upright_row,
    "v_up" to Res.drawable.coach_artur_v_up,
    "wall_sit" to Res.drawable.coach_artur_wall_sit,
    "wide_pullup" to Res.drawable.coach_artur_wide_pullup,
    "wide_pushup" to Res.drawable.coach_artur_wide_pushup,
    "world_greatest_stretch" to Res.drawable.coach_artur_world_greatest_stretch,
)

private val miaExerciseIllustrations = mapOf(
    "squat" to Res.drawable.coach_mia_squat,
    "leg_press" to Res.drawable.coach_mia_leg_press,
    "lunge" to Res.drawable.coach_mia_lunge,
    "deadlift" to Res.drawable.coach_mia_deadlift,
    "hip_thrust" to Res.drawable.coach_mia_hip_thrust,
    "bench" to Res.drawable.coach_mia_bench,
    "pushup" to Res.drawable.coach_mia_pushup,
    "dip" to Res.drawable.coach_mia_dip,
    "row" to Res.drawable.coach_mia_row,
    "pullup" to Res.drawable.coach_mia_pullup,
    "ohp" to Res.drawable.coach_mia_ohp,
    "curl" to Res.drawable.coach_mia_curl,
    "tricep_extension" to Res.drawable.coach_mia_tricep_extension,
    "run" to Res.drawable.coach_mia_run,
    "bike" to Res.drawable.coach_mia_bike,
    "ab_wheel" to Res.drawable.coach_mia_ab_wheel,
    "arnold_press" to Res.drawable.coach_mia_arnold_press,
    "assisted_pullup" to Res.drawable.coach_mia_assisted_pullup,
    "band_pulldown" to Res.drawable.coach_mia_band_pulldown,
    "band_row" to Res.drawable.coach_mia_band_row,
    "barbell_hack_squat" to Res.drawable.coach_mia_barbell_hack_squat,
    "battle_rope" to Res.drawable.coach_mia_battle_rope,
    "bicycle_crunch" to Res.drawable.coach_mia_bicycle_crunch,
    "box_jump" to Res.drawable.coach_mia_box_jump,
    "box_squat" to Res.drawable.coach_mia_box_squat,
    "bulgarian_split_squat" to Res.drawable.coach_mia_bulgarian_split_squat,
    "burpee" to Res.drawable.coach_mia_burpee,
    "cable_crunch" to Res.drawable.coach_mia_cable_crunch,
    "cable_curl" to Res.drawable.coach_mia_cable_curl,
    "cable_fly" to Res.drawable.coach_mia_cable_fly,
    "cable_row" to Res.drawable.coach_mia_cable_row,
    "cat_cow" to Res.drawable.coach_mia_cat_cow,
    "chest_supported_row" to Res.drawable.coach_mia_chest_supported_row,
    "chin_up" to Res.drawable.coach_mia_chin_up,
    "close_grip_bench" to Res.drawable.coach_mia_close_grip_bench,
    "concentration_curl" to Res.drawable.coach_mia_concentration_curl,
    "crunch" to Res.drawable.coach_mia_crunch,
    "dead_bug" to Res.drawable.coach_mia_dead_bug,
    "decline_pushup" to Res.drawable.coach_mia_decline_pushup,
    "diamond_pushup" to Res.drawable.coach_mia_diamond_pushup,
    "dumbbell_fly" to Res.drawable.coach_mia_dumbbell_fly,
    "dumbbell_row" to Res.drawable.coach_mia_dumbbell_row,
    "dumbbell_shoulder_press" to Res.drawable.coach_mia_dumbbell_shoulder_press,
    "elliptical" to Res.drawable.coach_mia_elliptical,
    "face_pull" to Res.drawable.coach_mia_face_pull,
    "foam_rolling" to Res.drawable.coach_mia_foam_rolling,
    "front_raise" to Res.drawable.coach_mia_front_raise,
    "front_squat" to Res.drawable.coach_mia_front_squat,
    "glute_bridge" to Res.drawable.coach_mia_glute_bridge,
    "goblet_squat" to Res.drawable.coach_mia_goblet_squat,
    "good_morning" to Res.drawable.coach_mia_good_morning,
    "hack_squat" to Res.drawable.coach_mia_hack_squat,
    "hammer_curl" to Res.drawable.coach_mia_hammer_curl,
    "handstand_pushup" to Res.drawable.coach_mia_handstand_pushup,
    "hanging_leg_raise" to Res.drawable.coach_mia_hanging_leg_raise,
    "high_knees" to Res.drawable.coach_mia_high_knees,
    "hip_flexor_stretch" to Res.drawable.coach_mia_hip_flexor_stretch,
    "hollow_body" to Res.drawable.coach_mia_hollow_body,
    "incline_bench" to Res.drawable.coach_mia_incline_bench,
    "incline_curl" to Res.drawable.coach_mia_incline_curl,
    "incline_pushup" to Res.drawable.coach_mia_incline_pushup,
    "inverted_row" to Res.drawable.coach_mia_inverted_row,
    "jump_rope" to Res.drawable.coach_mia_jump_rope,
    "jump_squat" to Res.drawable.coach_mia_jump_squat,
    "jumping_jack" to Res.drawable.coach_mia_jumping_jack,
    "kettlebell_swing" to Res.drawable.coach_mia_kettlebell_swing,
    "l_sit" to Res.drawable.coach_mia_l_sit,
    "lat_pulldown" to Res.drawable.coach_mia_lat_pulldown,
    "lateral_lunge" to Res.drawable.coach_mia_lateral_lunge,
    "lateral_raise" to Res.drawable.coach_mia_lateral_raise,
    "leg_curl" to Res.drawable.coach_mia_leg_curl,
    "leg_extension" to Res.drawable.coach_mia_leg_extension,
    "leg_raise" to Res.drawable.coach_mia_leg_raise,
    "mountain_climber" to Res.drawable.coach_mia_mountain_climber,
    "muscle_up" to Res.drawable.coach_mia_muscle_up,
    "nordic_curl" to Res.drawable.coach_mia_nordic_curl,
    "pike_pushup" to Res.drawable.coach_mia_pike_pushup,
    "pistol_squat" to Res.drawable.coach_mia_pistol_squat,
    "plank" to Res.drawable.coach_mia_plank,
    "reverse_curl" to Res.drawable.coach_mia_reverse_curl,
    "reverse_lunge" to Res.drawable.coach_mia_reverse_lunge,
    "romanian_deadlift" to Res.drawable.coach_mia_romanian_deadlift,
    "rowing_machine" to Res.drawable.coach_mia_rowing_machine,
    "russian_twist" to Res.drawable.coach_mia_russian_twist,
    "side_plank" to Res.drawable.coach_mia_side_plank,
    "single_leg_deadlift" to Res.drawable.coach_mia_single_leg_deadlift,
    "skater_jump" to Res.drawable.coach_mia_skater_jump,
    "skater_lunge" to Res.drawable.coach_mia_skater_lunge,
    "skull_crusher" to Res.drawable.coach_mia_skull_crusher,
    "sprint" to Res.drawable.coach_mia_sprint,
    "stair_climb" to Res.drawable.coach_mia_stair_climb,
    "step_up" to Res.drawable.coach_mia_step_up,
    "stretching" to Res.drawable.coach_mia_stretching,
    "sumo_deadlift" to Res.drawable.coach_mia_sumo_deadlift,
    "sumo_squat" to Res.drawable.coach_mia_sumo_squat,
    "swim" to Res.drawable.coach_mia_swim,
    "t_bar_row" to Res.drawable.coach_mia_t_bar_row,
    "toes_to_bar" to Res.drawable.coach_mia_toes_to_bar,
    "tricep_kickback" to Res.drawable.coach_mia_tricep_kickback,
    "tricep_pushdown" to Res.drawable.coach_mia_tricep_pushdown,
    "upright_row" to Res.drawable.coach_mia_upright_row,
    "v_up" to Res.drawable.coach_mia_v_up,
    "wall_sit" to Res.drawable.coach_mia_wall_sit,
    "wide_pullup" to Res.drawable.coach_mia_wide_pullup,
    "wide_pushup" to Res.drawable.coach_mia_wide_pushup,
    "world_greatest_stretch" to Res.drawable.coach_mia_world_greatest_stretch,
)

private val vtempeExerciseIllustrations = mapOf(
    "squat" to Res.drawable.coach_vtempe_squat,
    "leg_press" to Res.drawable.coach_vtempe_leg_press,
    "lunge" to Res.drawable.coach_vtempe_lunge,
    "deadlift" to Res.drawable.coach_vtempe_deadlift,
    "hip_thrust" to Res.drawable.coach_vtempe_hip_thrust,
    "bench" to Res.drawable.coach_vtempe_bench,
    "pushup" to Res.drawable.coach_vtempe_pushup,
    "dip" to Res.drawable.coach_vtempe_dip,
    "row" to Res.drawable.coach_vtempe_row,
    "pullup" to Res.drawable.coach_vtempe_pullup,
    "ohp" to Res.drawable.coach_vtempe_ohp,
    "curl" to Res.drawable.coach_vtempe_curl,
    "tricep_extension" to Res.drawable.coach_vtempe_tricep_extension,
    "plank" to Res.drawable.coach_vtempe_plank,
    "run" to Res.drawable.coach_vtempe_run,
    "bike" to Res.drawable.coach_vtempe_bike,
    "ab_wheel" to Res.drawable.coach_vtempe_ab_wheel,
    "arnold_press" to Res.drawable.coach_vtempe_arnold_press,
    "assisted_pullup" to Res.drawable.coach_vtempe_assisted_pullup,
    "band_pulldown" to Res.drawable.coach_vtempe_band_pulldown,
    "band_row" to Res.drawable.coach_vtempe_band_row,
    "barbell_hack_squat" to Res.drawable.coach_vtempe_barbell_hack_squat,
    "battle_rope" to Res.drawable.coach_vtempe_battle_rope,
    "bicycle_crunch" to Res.drawable.coach_vtempe_bicycle_crunch,
    "box_jump" to Res.drawable.coach_vtempe_box_jump,
    "box_squat" to Res.drawable.coach_vtempe_box_squat,
    "bulgarian_split_squat" to Res.drawable.coach_vtempe_bulgarian_split_squat,
    "burpee" to Res.drawable.coach_vtempe_burpee,
    "cable_crunch" to Res.drawable.coach_vtempe_cable_crunch,
    "cable_curl" to Res.drawable.coach_vtempe_cable_curl,
    "cable_fly" to Res.drawable.coach_vtempe_cable_fly,
    "cable_row" to Res.drawable.coach_vtempe_cable_row,
    "cat_cow" to Res.drawable.coach_vtempe_cat_cow,
    "chest_supported_row" to Res.drawable.coach_vtempe_chest_supported_row,
    "chin_up" to Res.drawable.coach_vtempe_chin_up,
    "close_grip_bench" to Res.drawable.coach_vtempe_close_grip_bench,
    "concentration_curl" to Res.drawable.coach_vtempe_concentration_curl,
    "crunch" to Res.drawable.coach_vtempe_crunch,
    "dead_bug" to Res.drawable.coach_vtempe_dead_bug,
    "decline_pushup" to Res.drawable.coach_vtempe_decline_pushup,
    "diamond_pushup" to Res.drawable.coach_vtempe_diamond_pushup,
    "dumbbell_fly" to Res.drawable.coach_vtempe_dumbbell_fly,
    "dumbbell_row" to Res.drawable.coach_vtempe_dumbbell_row,
    "dumbbell_shoulder_press" to Res.drawable.coach_vtempe_dumbbell_shoulder_press,
    "elliptical" to Res.drawable.coach_vtempe_elliptical,
    "face_pull" to Res.drawable.coach_vtempe_face_pull,
    "foam_rolling" to Res.drawable.coach_vtempe_foam_rolling,
    "front_raise" to Res.drawable.coach_vtempe_front_raise,
    "front_squat" to Res.drawable.coach_vtempe_front_squat,
    "glute_bridge" to Res.drawable.coach_vtempe_glute_bridge,
    "goblet_squat" to Res.drawable.coach_vtempe_goblet_squat,
    "good_morning" to Res.drawable.coach_vtempe_good_morning,
    "hack_squat" to Res.drawable.coach_vtempe_hack_squat,
    "hammer_curl" to Res.drawable.coach_vtempe_hammer_curl,
    "handstand_pushup" to Res.drawable.coach_vtempe_handstand_pushup,
    "hanging_leg_raise" to Res.drawable.coach_vtempe_hanging_leg_raise,
    "high_knees" to Res.drawable.coach_vtempe_high_knees,
    "hip_flexor_stretch" to Res.drawable.coach_vtempe_hip_flexor_stretch,
    "hollow_body" to Res.drawable.coach_vtempe_hollow_body,
    "incline_bench" to Res.drawable.coach_vtempe_incline_bench,
    "incline_curl" to Res.drawable.coach_vtempe_incline_curl,
    "incline_pushup" to Res.drawable.coach_vtempe_incline_pushup,
    "inverted_row" to Res.drawable.coach_vtempe_inverted_row,
    "jump_rope" to Res.drawable.coach_vtempe_jump_rope,
    "jump_squat" to Res.drawable.coach_vtempe_jump_squat,
    "jumping_jack" to Res.drawable.coach_vtempe_jumping_jack,
    "kettlebell_swing" to Res.drawable.coach_vtempe_kettlebell_swing,
    "l_sit" to Res.drawable.coach_vtempe_l_sit,
    "lat_pulldown" to Res.drawable.coach_vtempe_lat_pulldown,
    "lateral_lunge" to Res.drawable.coach_vtempe_lateral_lunge,
    "lateral_raise" to Res.drawable.coach_vtempe_lateral_raise,
    "leg_curl" to Res.drawable.coach_vtempe_leg_curl,
    "leg_extension" to Res.drawable.coach_vtempe_leg_extension,
    "leg_raise" to Res.drawable.coach_vtempe_leg_raise,
    "mountain_climber" to Res.drawable.coach_vtempe_mountain_climber,
    "muscle_up" to Res.drawable.coach_vtempe_muscle_up,
    "nordic_curl" to Res.drawable.coach_vtempe_nordic_curl,
    "pike_pushup" to Res.drawable.coach_vtempe_pike_pushup,
    "pistol_squat" to Res.drawable.coach_vtempe_pistol_squat,
    "reverse_curl" to Res.drawable.coach_vtempe_reverse_curl,
    "reverse_lunge" to Res.drawable.coach_vtempe_reverse_lunge,
    "romanian_deadlift" to Res.drawable.coach_vtempe_romanian_deadlift,
    "rowing_machine" to Res.drawable.coach_vtempe_rowing_machine,
    "russian_twist" to Res.drawable.coach_vtempe_russian_twist,
    "side_plank" to Res.drawable.coach_vtempe_side_plank,
    "single_leg_deadlift" to Res.drawable.coach_vtempe_single_leg_deadlift,
    "skater_jump" to Res.drawable.coach_vtempe_skater_jump,
    "skater_lunge" to Res.drawable.coach_vtempe_skater_lunge,
    "skull_crusher" to Res.drawable.coach_vtempe_skull_crusher,
    "sprint" to Res.drawable.coach_vtempe_sprint,
    "stair_climb" to Res.drawable.coach_vtempe_stair_climb,
    "step_up" to Res.drawable.coach_vtempe_step_up,
    "stretching" to Res.drawable.coach_vtempe_stretching,
    "sumo_deadlift" to Res.drawable.coach_vtempe_sumo_deadlift,
    "sumo_squat" to Res.drawable.coach_vtempe_sumo_squat,
    "swim" to Res.drawable.coach_vtempe_swim,
    "t_bar_row" to Res.drawable.coach_vtempe_t_bar_row,
    "toes_to_bar" to Res.drawable.coach_vtempe_toes_to_bar,
    "tricep_kickback" to Res.drawable.coach_vtempe_tricep_kickback,
    "tricep_pushdown" to Res.drawable.coach_vtempe_tricep_pushdown,
    "upright_row" to Res.drawable.coach_vtempe_upright_row,
    "v_up" to Res.drawable.coach_vtempe_v_up,
    "wall_sit" to Res.drawable.coach_vtempe_wall_sit,
    "wide_pullup" to Res.drawable.coach_vtempe_wide_pullup,
    "wide_pushup" to Res.drawable.coach_vtempe_wide_pushup,
    "world_greatest_stretch" to Res.drawable.coach_vtempe_world_greatest_stretch,
)
